# Generated by Django 2.0.6 on 2018-07-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('url_file', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=300)),
                ('access_right_ids', models.ManyToManyField(to='biblioteca_sistedes.AccessRight')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('article_ids', models.ManyToManyField(to='biblioteca_sistedes.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_sistedes.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article_ids', models.ManyToManyField(to='biblioteca_sistedes.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article_ids', models.ManyToManyField(to='biblioteca_sistedes.Article')),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_sistedes.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.IntegerField()),
                ('edition_ids', models.ManyToManyField(to='biblioteca_sistedes.Edition')),
                ('track_ids', models.ManyToManyField(to='biblioteca_sistedes.Track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='user_ids',
            field=models.ManyToManyField(to='biblioteca_sistedes.User'),
        ),
        migrations.AddField(
            model_name='edition',
            name='user_ids',
            field=models.ManyToManyField(to='biblioteca_sistedes.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_ids',
            field=models.ManyToManyField(to='biblioteca_sistedes.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword_ids',
            field=models.ManyToManyField(to='biblioteca_sistedes.Keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='track_ids',
            field=models.ManyToManyField(to='biblioteca_sistedes.Track'),
        ),
        migrations.AddField(
            model_name='accessright',
            name='article_ids',
            field=models.ManyToManyField(to='biblioteca_sistedes.Article'),
        ),
    ]
