# Generated by Django 2.0.6 on 2018-07-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_sistedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
